FROM kong:0.14.1-alpine
COPY ./kongconf/kong.beta.conf /etc/kong/
COPY ./kongconf/kong.dev.conf /etc/kong/
COPY ./kongconf/kong.pro.conf /etc/kong/

COPY ./custom-kong-entrypoint.sh /
RUN luarocks install kong-plugin-replace-url && \
    luarocks install kong-oidc && \
    luarocks install https://github.com/wego/kong-jwt-claim-headers/releases/download/v1.0.0/kong-jwt-claim-headers-1.0-1.src.rock

RUN rm -rf /usr/local/share/lua/5.1/kong/plugins/jwt-claim-headers/claim_headers.lua
COPY ./claim_headers.lua /usr/local/share/lua/5.1/kong/plugins/jwt-claim-headers/claim_headers.lua

ENTRYPOINT ["/custom-kong-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]